# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieFlix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieFlix
  pod 'ChameleonFramework'
  pod 'BonMot'
  pod 'Hero' , :git => 'https://github.com/lkzhao/Hero'
  pod 'SwiftIcons', :git => 'https://github.com/ranesr/SwiftIcons'
  pod 'HCSStarRatingView'
  pod 'XLPagerTabStrip'
  pod 'BMPlayer'
  pod 'Moya'
  pod 'SnapKit'
  pod 'YoutubeSourceParserKit' , :git => 'https://github.com/lennet/YoutubeSourceParserKit', :branch => 'master'
  pod 'Kingfisher'

  target 'MovieFlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieFlixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
